# TODO Create your inputs, variables, and add your story here!
noun=input("enter a noun: ")
print(noun)
adjective=input("enter an adjective: ")
print(adjective)
verb=input("enter a verb: ")
print(verb)

#add 10 more inputs and update your story along the way
name=input("enter a name: ")
print(name)
noun2=input("enter another noun: ")
print(noun2)
place=input("enter a location: ")
print(place)
verb2=input("enter a verb: ")
print(verb2)
noun3=input("enter a noun: ")
print(noun3)
verb3=input("enter a verb: ")
print(verb3)
adjective2=input("enter an adjective: ")
print(adjective2)
place2=input("enter a location: ")
print(place2)
print(f"{noun} was {adjective} while {verb}. Later that day, {name} and {noun2} went to {place} and {verb2}. Then they noticed a {noun3} {verb3} at them. They got {adjective2} and went {place2}.")
